version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: 3cket_app
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=laravel_app"
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: 3cket_web
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: 3cket_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
